### ISSUE TITLE
Cannot log into gihub from the latest build page

### ISSUE THREAD

**Issue by MikeDX** [sehugg/8bitworkshop#108]
Accessing the IDE from the url https://sehugg.github.io/8bitworkshop does not allow signing into github due to a domain restriction

![Screenshot 2022-07-13 at 00 04 37](https://user-images.githubusercontent.com/853931/178613081-9568a332-28c6-4fb3-9b7a-7f2a9f8cb757.png)

Hopefully this is something that can easily be resolved via a configuration setting (not directly related to the IDE) in firebase.

**Comment by sehugg** [comment]
Yep it was a config setting. Should work now, as long as you allow pop-ups.
