### ISSUE TITLE
graphics corruption on Firefox for the non-asm NES examples

### ISSUE THREAD

**Issue by irmen** [sehugg/8bitworkshop#12]
- NES
- Hello World example
- Firefox 66 on Linux gives the below result:
![image](https://user-images.githubusercontent.com/1771820/64912140-4e602480-d72b-11e9-8217-d80f30bc8733.png)
- similar corruptions can be observed in the other C-based examples.  The ASM-code examples seem to work fine.
- the example is okay when running in Chrome on the same system.

**Comment by sehugg** [comment]
That's a weird one. Can you try it in a Private window?

I wonder though if WebAssembly isn't enabled. If you hit Ctrl-Shift-I to view the console, see if it says "Loaded cc65.wasm (343765 bytes)" when compiling a C example.

**Comment by irmen** [comment]
Yeah it has loaded the various wasm modules.
Interestingly, running it in a private window fixes the issue.  
I wiped my browser's cache and website storage data and reloaded the page, and now the issue is gone.   Odd that some cached data could cause this?   
But anyway, problem is gone, i'll close this issue
