### ISSUE TITLE
Editing linker cfg for NES

### ISSUE THREAD

**Issue by Memblers** [sehugg/8bitworkshop#15]
I was hoping to edit the linker config.  I took the src/worker/lib/nes/neslib2.cfg file, renamed it, and used GitHub's web interface to upload the file into my repo.  In my main C source file I added:
//#resource "example.cfg"
//#define CFGFILE example.cfg

The config file is listed in the project, but opening it causes an error message, and leaves the editor portion of the screen glitched and unusable.
TypeError: a.match is not a function https://8bitworkshop.com/v3.4.2/src/codemirror/codemirror.js (36:356)

I'll see if I can just edit it outside the IDE and continue that way, but it can be a bit of a land-mine while it's in the file list.

It's a really nice IDE, I like it!

**Comment by sehugg** [comment]
Huh. Looks like it is a problem with the editor, specifically when pasting in "    CONDES: type    = constructor". I think there's a bug in the 6502 asm highlighter.

**Comment by sehugg** [comment]
Eww, it's actually the symbol "constructor" -- every JS object responds to obj['constructor'] with a function object, which confuses the tokenizer :/ Fixed in version 3.5.0.
