### ISSUE TITLE
Atari Color Vector (6502) Issues

### ISSUE THREAD

**Issue by MikeDX** [sehugg/8bitworkshop#158]
Couple of problems running the Atari Color Vector examples on the latest build (v3.10.0)

# Vector fonts 

Refuses to run without a modification to vecfont.h

Changing 

```
const word* const VECFONT[];
```

to

```
extern const word* const VECFONT[];
```

This stopped the following error (warning) appearing and preventing the demo from running:

```
(font.c:38) Warning: Incomplete array 'VECFONT[]' assumed to have one element
```

# 3D Transformations

wont compile: Error

```
(vec3d.c:18) Error: Call to undeclared function 'cc65_imul8x8r16'
```

# Space Game

lots of issues:

```
(game.c:190) Error: Call to undeclared function 'cc65_imul8x8r16'

(game.c:252) Error: Expression expected

(game.c:252) Error: '}' expected

(game.c:255) Error: Expression expected

(game.c:255) Error: '}' expected

(game.c:258) Error: Expression expected

(game.c:258) Error: '}' expected

(game.c:261) Error: Expression expected

(game.c:261) Error: '}' expected

(game.c:397) Warning: Incomplete array 'VECFONT[]' assumed to have one element
```

# Pokey Music
```
Could not find file "music.c". Loading default file.
```

Completely missing the file?

**Comment by sehugg** [comment]
Most of those are fixed in the main branch except for the missing POKEY music.c: https://sehugg.github.io/8bitworkshop/?platform=vector-ataricolor&file=font.c
