### ISSUE TITLE
Apple ][ keyboard broken

### ISSUE THREAD

**Issue by sehugg** [sehugg/8bitworkshop#160]
- becomes =, ' becomes ^, shift-9 produces 9 rather than (, etc.

**Comment by sehugg** [comment]
The keyboard handler function is still using 'which' and 'keyCode' properties on the event, which have been deprecated since forever.

The new cool way is to use the 'key' and 'code' but that would break everything probably, esp. b/c they are strings not integers. But it would be nice to replace those large switch statements in apple2, c64, atari8, etc.

**Comment by sehugg** [comment]
Apple2 was using the keyPress event, and we now only support keyDown/keyUp. Problem is that those do not return ASCII codes when using the shift key, so we have to hand-code case statements, at least until we move to key/code properties. Fixed in dev.

**Comment by micahcowan** [comment]
I appreciate you noticing and fixing this. Meant to look into what was going on myself, as it was impacting me somewhat (but I'd just been working around it). Kudos!
