### ISSUE TITLE
Support Z and X keys as buttons A/B for NES/7800/etc

### ISSUE THREAD

**Issue by sehugg** [sehugg/8bitworkshop#167]
I changed from Z and X to Space and Shift to avoid conflicting with keyboards, but I think I could support both schemes on NES and 7800.

**Comment by langel** [comment]
It would be super cool if you could use both the analog stick and the d pad on the controller too. I just double checked and the NES emulator only responds to the analog stick.

**Comment by sehugg** [comment]
Might be working now here:

https://sehugg.github.io/8bitworkshop/?file=metacursor.c&platform=nes
