### ISSUE TITLE
How do I upload a .chr file into my project?

### ISSUE THREAD

**Issue by DigitEngine** [sehugg/8bitworkshop#18]
I am trying to upload a .chr file into my project, but I can't do it without opening it as a project.
How do i upload a .chr file to my project?

**Comment by sehugg** [comment]
There's a bug in binary file uploading I gotta fix. Clear your browser cache and go back to the IDE, then upload your file, then reload the browser page. It should show up at the bottom.

You have to convert it to .s or .c to link to a C program. In assembly you can use `incbin "foo.chr"` to include the binary directly.

**Comment by DigitEngine** [comment]
I got the file into my project, but there's an error in the assembly that says "Cannot open include file `tset.chr': No such file or directory"

**Comment by sehugg** [comment]
If you go to the pulldown and select the .chr file do you see the hex bytes?

There's another gotcha that incbin can't be used in include files, only the main file. (unless you use //#resource but that's another story...)

**Comment by DigitEngine** [comment]
I do, but whenever reload the page/go to another project and go back, the file isn't there anymore. I think it might have to do with the fact that I got the file like this: opened file as project, went back to my project, made new include file, and then typed in the filename ("tset.chr"), because that's the only way it seemed to work.

**Comment by sehugg** [comment]
Are you using 8bitworkshop.com/v3.4.2 ?

Also do you mean the file disappears from the pulldown or the left side bar?

**Comment by DigitEngine** [comment]
yes and yes.

**Comment by DigitEngine** [comment]
Wait!!!! I just used '//#resource' for it and it worked!!!

**Comment by sehugg** [comment]
`#resource` forces the IDE to include a file in your project, but `[.]incbin`, `#link` and `[#]include` should include their files too. If you export to GitHub I can look further. Glad it worked!

**Comment by DigitEngine** [comment]
Okay. Thanks for all your help!
