### ISSUE TITLE
make *.nes export feature

### ISSUE THREAD

**Issue by DigitEngine** [sehugg/8bitworkshop#19]
This isn't actually an issue, but is there any possibility that you could add a feature that exports the NES program to a *.nes file instead of a *.rom file? And, if you have any recommendations for programs that can do this, what are they? (I'd rather do the first option, because of the directives that only work in the 8bitworkshop IDE.)

**Comment by sehugg** [comment]
I think you can rename the .rom to .nes, no? (i.e. they're both ROMs with a iNES header)

**Comment by DigitEngine** [comment]
Cool! I changed the file type and opened it in Mesen and it showed up. Somehow I knew subconsciously that that would end up being the solution. Don't know why I didn't try that! >:(
I am very curious, so that surprises me. Thanks!
