### ISSUE TITLE
More nametables for side-scrolling platformers

### ISSUE THREAD

**Issue by DigitEngine** [sehugg/8bitworkshop#20]
Is there any way to have more nametables to the right of nametable B, like a side-scrolling platformer
would? (btw sorry i keep making issues, i just need help with stuff that i don't think is in the book)

**Comment by sehugg** [comment]
The "Offscreen Scrolling" example shows how this is done: https://8bitworkshop.com/v3.4.2/?file=horizscroll.c&platform=nes

Nesdoug's game has a simple horizontal platformer: https://8bitworkshop.com/projects/?n=nes/nesdoug_25

(BTW you can reach me at https://twitter.com/8bitworkshop too. I've also found the folks on the NesDev forums helpful: https://forums.nesdev.com/viewforum.php?f=2 and possibly the Discord https://discordapp.com/invite/pTWwBCp)

**Comment by DigitEngine** [comment]
I've looked over the code and know how it works. But there is one thing: how do you fill the vertical slice of nametable data with something that isn't random?
