### ISSUE TITLE
Apple II palette broken in 3.5.0

### ISSUE THREAD

**Issue by cybernesto** [sehugg/8bitworkshop#28]
The Apple II palette looked right in version 3.4.2. The HGR Test would cycle through green and magenta as expected on real hardware. Version 3.5.0 shows some strange red instead.

**Comment by sehugg** [comment]
I grabbed the lo-res LUT from an old USENET post: https://mrob.com/pub/xapple2/colors.html

Not sure what other Apple ][ emulators use, maybe that's something to investigate.

**Comment by cybernesto** [comment]
Yes, that is a very accurate color table. I also use it for DHGR image conversion. But I suppose you chose the wrong colors. From the big table you have to use the ones marked with HCOLOR:

 purple   HCOLOR=2  45 100   50    255  68 253
 orange   HCOLOR=5 135 100   50    255 106  60
 green    HCOLOR=1 225 100   50     20 245  60
 blue     HCOLOR=6 315 100   50     20 207 253

**Comment by cybernesto** [comment]
Sent you a pull req.
