### ISSUE TITLE
ifconfig is deprecated and should be replaced with "ip addr" in the Makefile

### ISSUE THREAD

**Issue by SSBMTonberry** [sehugg/8bitworkshop#39]
Hello!
First of all I want to thank you for this awesome piece of software and the best NESDEV book ever made!

I am an Arch Linux user. If you are familiar with Arch Linux, you know the bleeding edge nature of the system. `ifconfig` has been deprecated for a while, and is in fact no longer existing in Arch Linux, thus I had some problems coming up when i tried to call `make tsweb`. I solved this by simply replacing `ifconfig` with `ip addr` for both the web and tsweb-part.

Is this a change you would consider doing?

This is how the web and tsweb looks like in my Makefile now:
```
web:
	ip addr | grep inet
	python3 scripts/serveit.py 2>> /dev/null #http.out

tsweb:
	ip addr | grep inet
	$(TSC) -w &
	python3 scripts/serveit.py 2>> /dev/null #http.out
```

Edit: I can of course also do a pull request on this change, if you want.

**Comment by sehugg** [comment]
The call to ifconfig is purely informational (b/c on my Chromebook I need to see the IP address of the web server endpoint) so does this change work?

(ip addr || ifconfig) | grep inet

**Comment by SSBMTonberry** [comment]
@sehugg: That solution seems to work fine on my machine :)
Yeah, you're probably right that OSX might not support that command.
