### ISSUE TITLE
Error on publish to GitHub

### ISSUE THREAD

**Issue by F8Sean** [sehugg/8bitworkshop#57]
Could not push GitHub repository: Error: { "message": "Not Found", "documentation_url": "https://docs.github.com/enterprise/2.18/user/rest/reference/git#get-a-reference" } GET https://api.github.com/repos/F8Sean/c64demo/git/refs/heads/master Status: 404

I get this same error on any GitHub action, creating a new repo, uploading to a repo, etc

Is this an issue with my GitHub account?

**Comment by sehugg** [comment]
Sorry about that, the IDE assumed the name of the default branch but now it checks first. Try the new 3.7.1 version and see if it fixes it.

**Comment by F8Sean** [comment]
That was it, thanks!
