### ISSUE TITLE
Can anybody import a project into 8BWS ? sess is undefined...

### ISSUE THREAD

**Issue by tilleul** [sehugg/8bitworkshop#58]
When you publish/create a project on github, there's a link in README.md that proposes to open the project in 8bitworkshop. I think it's a great feature to share your code with others but it does not seem possible for someone other than me to do so ... as others receive an error "could not import (project). sess is undefined"  ..

Am I missing something ? Thanks for such a wonderful tool !

**Comment by sehugg** [comment]
Try it now (may have to clear browser cache)

**Comment by tilleul** [comment]
yes it works ! fantastic ! thank you !
