### ISSUE TITLE
Feature request: support MADS assembler

### ISSUE THREAD

**Issue by TheRealCatherine** [sehugg/8bitworkshop#6]
I would love it if maybe there was a VCS (MADS) platform or maybe an Assembler option under the Platform selection that allowed using the MADS assembler (http://mads.atari8.info/ ) I've used this in the WUDSN IDE and it seems to work fine for 2600 development.

Obviously this goes beyond the scope of this being a book-support tool and would mean it moving toward being a real development tool so I consider this request a bit of a long shot but I hope you consider it!

Thanks so much for making this awesome tool and the wonderfully informative book!

**Comment by TheRealCatherine** [comment]
If this feature add request is considered, I have started porting the examples to MADS here: https://github.com/TheRealCatherine/MakingGamesForAtari2600-MADS

**Comment by sehugg** [comment]
Any assemblers need to be in JS or compiled with Emscripten -- since MADS is a Delphi app I don't think that can happen.
