### ISSUE TITLE
opening memory browser crashes the ide

### ISSUE THREAD

**Issue by NotExactlySiev** [sehugg/8bitworkshop#67]
I'm working on an NES game and after some point during the development, opening memory browser started to immediately crash the entire website. It works completely fine for all other files, NES or not. I'm using Firefox on Manjaro Linux and switching the web browser didn't change anything. Here's my project if you want to try and replicate the issue: https://github.com/NotExactlySiev/psychofloat
Just importing it and opening memory browser should do the trick, unless it's a problem on my side.

**Comment by sehugg** [comment]
Looks like the asm symbols with values > $FFFF confused it. If you do a forced refresh (ctrl-shift-R or similar) it should be fixed. The game looks interesting btw!
