### ISSUE TITLE
MSX BIOS Wrong implementation of WRTPSG call

### ISSUE THREAD

**Issue by albs-br** [sehugg/8bitworkshop#77]
Hi guys, congrats for the great job!

Just found a small bug:
The implementation of the call WRTPSG were using the wrong address, 0x0096 instead of 0x0093:

https://8bitworkshop.com/v3.8.0/?repo=albs-br%2Farya&platform=msx&file=main.c#

Code snippet:
```
uint16_t WRTPSG(uint16_t reg_data) __z88dk_fastcall {
  reg_data;
  MSXUSR_LOAD_A();
  MSXUSR_LOAD_E();
  //MSXUSR(0x0096);
  MSXUSR(0x0093);
}
```

MSX BIOS calls can be checked here: http://map.grauw.nl/resources/msxbios.php

Also, the IDE running on Chrome doesn't have sound at all. If I download the ROM and run on emulator the sounds is OK. Not sure if this problem is on my machine.

**Comment by sehugg** [comment]
Good catch, I fixed a few other BIOS calls as well, but haven't exhaustively tested. It'll be in a future update.

The sound on Chrome is another issue -- could be related to [autoplay behavior](https://developer.chrome.com/blog/autoplay/), I wonder if you pause and resume will it come back?

**Comment by albs-br** [comment]
That's right, after clicking on output window, the sound works fine.
