### ISSUE TITLE
Travis build is broken - Property 'msOrientation' does not exist on type 'Screen'

### ISSUE THREAD

**Issue by felipesanches** [sehugg/8bitworkshop#8]
https://travis-ci.org/sehugg/8bitworkshop/builds/477407745

![screenshot at 2019-01-25 16 33 53](https://user-images.githubusercontent.com/213676/51765584-12ab1880-20d0-11e9-8538-1bf294440b9b.png)

**Comment by sehugg** [comment]
I think this got fixed recently. Thanks.
